Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Rails/Date:
  Enabled: false

Security/YAMLLoad:
  Enabled: false