Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Rails/Date:
  Enabled: false

Security/YAMLLoad:
  Enabled: false